name: Recuperation Automatique Tally
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch and Process
        run: |
          mkdir -p content/fanzines
          # On crée un fichier témoin pour éviter l'erreur "pas de fichiers"
          echo "Dernier passage du robot : $(date)" > content/fanzines/_last_sync.txt
          
          # Tentative de récupération des données
          curl -s "https://api.tally.so/forms/441GVB/submissions" > data.json

      - name: Commit and Push
        run: |
          git config --global user.name "Tally Bot"
          git config --global user.email "bot@tally.so"
          git add content/fanzines/
          git commit -m "Synchro Tally" || echo "Rien à synchroniser"
          git push
